//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinIT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoinIT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Commands.
        /// </summary>
        public static string AdditionalCommands {
            get {
                return ResourceManager.GetString("AdditionalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Operations.
        /// </summary>
        public static string AdditionalOperations {
            get {
                return ResourceManager.GetString("AdditionalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App will restart to apply changes.
        /// </summary>
        public static string AppRestart {
            get {
                return ResourceManager.GetString("AppRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Students.
        /// </summary>
        public static string AttachStudents {
            get {
                return ResourceManager.GetString("AttachStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font Size.
        /// </summary>
        public static string ChangeFontSize {
            get {
                return ResourceManager.GetString("ChangeFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font Size Button.
        /// </summary>
        public static string ChangeFontSizeButton {
            get {
                return ResourceManager.GetString("ChangeFontSizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Information.
        /// </summary>
        public static string CourseInfo {
            get {
                return ResourceManager.GetString("CourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Tab.
        /// </summary>
        public static string CoursesTab {
            get {
                return ResourceManager.GetString("CoursesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Tab.
        /// </summary>
        public static string CPlusPlusTab {
            get {
                return ResourceManager.GetString("CPlusPlusTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crud Operations.
        /// </summary>
        public static string CrudOperations {
            get {
                return ResourceManager.GetString("CrudOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Tab.
        /// </summary>
        public static string CSharpTab {
            get {
                return ResourceManager.GetString("CSharpTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Settings.
        /// </summary>
        public static string FontSettings {
            get {
                return ResourceManager.GetString("FontSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Tab.
        /// </summary>
        public static string JavaTab {
            get {
                return ResourceManager.GetString("JavaTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Tab.
        /// </summary>
        public static string LanguageTab {
            get {
                return ResourceManager.GetString("LanguageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Course Added.
        /// </summary>
        public static string NewCourseAdded {
            get {
                return ResourceManager.GetString("NewCourseAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Commands.
        /// </summary>
        public static string r {
            get {
                return ResourceManager.GetString("r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Settings Commands.
        /// </summary>
        public static string TextSettingsCommands {
            get {
                return ResourceManager.GetString("TextSettingsCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
